test workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,7 +38,15 @@ jobs:
     - name: Build Release APK
       run: |
         echo "SIGNING_KEY_ALIAS: $SIGNING_KEY_ALIAS"
-        echo "SIGNING_STORE_PASSWORD: ***"
+        echo "SIGNING_STORE_PASSWORD: $SIGNING_STORE_PASSWORD"
+        echo "Test if keystore.jks exists and is valid"
+        if [ -f "keystore.jks" ]; then
+          echo "✅ keystore.jks found!"
+          keytool -list -v -keystore keystore.jks -storepass $SIGNING_STORE_PASSWORD
+        else
+          echo "❌ keystore.jks not found!"
+          exit 1
+        fi
         ./gradlew assembleRelease --no-daemon
       env:
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
@@ -56,7 +64,7 @@ jobs:
           find ./app/build -name "*.apk" -type f
           exit 1
         fi
-        
+
     - name: Upload APK to Release
       uses: actions/upload-release-asset@v1
       env:
